# set environment
language: php

branches:
  only:
    - travis

    # php versions
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

# before runs environment
before_script:
  - chmod +x build.sh
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: ./build.sh
