# set environment
language: php

# php versions
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

# before runs environment
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# verify your build
script: phpunit

